---
- name: Copy nginx config file
  template: src=nginx.conf dest=/etc/nginx/sites-available
  notify: restart nginx

- name: Symlink config
  file: src=/etc/nginx/sites-available/nginx.conf dest=/etc/nginx/sites-enabled/default state=link

- name: Copy gunicorn config file
  template: src=gunicorn.conf dest={{ remote['gunicorn_conf_path'] }}
  notify: 
    - restart webapp
    - restart supervisor

- name: Copy supervisor config file
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/webapp.conf 
  notify: restart supervisor

- name: Configure django_manage
  template: src=django-manage dest=/usr/local/bin/django-manage mode="u=rwx,g=rx,o=rx"

