---
- name: Set environment
  template: src=env.j2 dest={{ remote['envs_path'] }}
  notify: restart webapp

- name: Copy private key
  copy: src={{ ssh_private_key_path }} dest={{ remote['private_key_path'] }} mode=0600
  when: ssh_private_key_path is defined

- name: Copy source from git
  git: repo={{ repo | mandatory }} dest={{ remote['git_root'] }} accept_hostkey=yes key_file={{ remote['private_key_path'] }}
  notify: restart webapp

- name: Install pip requirements
  pip: state=latest extra_args="-U" chdir={{ remote['git_root'] }} requirements={{ project_requirements_path | mandatory }} executable={{ python_config[python_version]['pip'] }}

- name: Run commands
  command: "{{ remote['django_manage_path'] }} {{ item }} --noinput"
  with_items: run_commands
