---
- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Install git
  apt: name=git state=present update_cache=yes

- name: Install supervisor
  apt: name=supervisor state=present update_cache=yes

- name: Install setuptools
  apt: name={{ python_config[python_version]['setuptools'] }} state=present update_cache=yes

- name: Install pip
  easy_install: name=pip executable={{ python_config[python_version]['easy_install'] }}

- name: Install database dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "{{ python_config[python_version]['python_dev'] }}"
    - "{{ python_config[python_version]['psycopg'] }}"
    - libpq-dev  
    - libmysqlclient-dev 
