---
- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Install git
  apt: name=git state=present update_cache=yes

- name: Install supervisor
  apt: name=supervisor state=present update_cache=yes

- name: Install setuptools
  apt: name=python3-setuptools state=present update_cache=yes

- name: Install pip
  easy_install: name=pip executable=easy_install-3.4

- name: Install psycopg2 dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python3-dev
    - python3-psycopg2
    - libpq-dev  
